#include "gm_brands.h"
#include "../protocols/gm_genie.h"

#include <furi.h>

/*
 * Pairing walkthroughs.
 *
 * Keep each body short enough to read on a 128x64 screen without fighting the
 * scrollbar -- roughly six lines. A step marked .transmit gets a Send button
 * wired to the radio by gm_scene_pair.c; the rest only page forward and back.
 */

static const GmPairStep steps_chamberlain_sp2[] = {
    {.title = "1. Find LEARN",
     "Stand under the motor unit on a ladder. Pop off the light lens if the "
     "back panel is hidden.\n\n"
     "Look for a square LEARN button next to the short antenna wire. On "
     "Security+ 2.0 units it is YELLOW."},
    {.title = "2. Press LEARN",
     "Press and release LEARN once. Do not hold it -- holding for 6+ seconds "
     "erases every remote you already own.\n\n"
     "The LED beside the button turns on. You now have about 30 seconds."},
    {.title = "3. Transmit",
     "Stand within a few feet of the motor unit.\n\n"
     "Press OK once to send the new remote code. On All bands it goes out on "
     "315, 310 and 390 MHz.\n\n"
     "One press only -- a second code would tell the door to reverse.",
     true},
    {.title = "4. Confirm",
     "The opener LED blinks or the lights flash once -- that means the remote "
     "was accepted.\n\n"
     "Nothing happened? Press BACK, check the frequency, and try again."},
};

static const GmPairStep steps_chamberlain_sp1[] = {
    {.title = "Use Add Manually",
     "Security+ 1.0 remotes cannot be generated by GarageMate: the firmware "
     "exposes no generator for this protocol.\n\n"
     "The stock Sub-GHz app can still make one."},
    {.title = "Create the remote",
     "Leave GarageMate. Open:\n"
     "Sub-GHz > Add Manually > Security+ 1.0\n\n"
     "Save it, then pair it using the opener's LEARN button (purple, red, "
     "orange or green on these units)."},
    {.title = "Bring it back",
     "Once saved, return here and use\n"
     "Add a door > Import saved .sub\n\n"
     "GarageMate will then list it alongside your other doors."},
};

static const GmPairStep steps_chamberlain_fixed[] = {
    {.title = "1. Check the DIPs",
     "Vintage Chamberlain openers use DIP switches, not rolling codes. The "
     "receiver simply learns whatever code it hears.\n\n"
     "No switch matching is needed -- we send a fresh random code."},
    {.title = "2. Press LEARN",
     "Press and release the LEARN or SMART button on the motor unit. The "
     "indicator LED lights up."},
    {.title = "3. Transmit",
     "Press OK to send the code. Stay close to the motor unit.",
     true},
    {.title = "4. Confirm",
     "The LED goes out or the lights blink. Test the door with the OPEN "
     "screen."},
};

static const GmPairStep steps_genie[] = {
    {.title = "1. How this works",
     "Genie's rolling code can't be generated -- only your own remote knows "
     "the sequence. So GarageMate learns codes from it over the air, then "
     "plays them back. You need your Genie remote."},
    {.title = "2. Leave the garage",
     "Move away from the garage, out of the opener's range (across the house "
     "or outside).\n\n"
     "This matters: codes you capture must be ones the opener has NOT seen, so "
     "it accepts them later."},
    {.title = "3. Learn codes",
     "On the next screen, hold your Genie remote near the Flipper and press "
     "its button several times. Each press adds one code.\n\n"
     "Capture 5-10, then press BACK.",
     true},
    {.title = "4. At the garage",
     "Come back and press OPEN. The Flipper sends the next learned code and "
     "the opener re-syncs to it.\n\n"
     "When the batch runs low, learn again. Your real remote keeps working."},
    {.title = "Older Genie?",
     "Genie units from before roughly 1995 use DIP switches, not Intellicode. "
     "If yours has a row of little switches, pick\n"
     "'Fixed-code gate' instead -- no capture needed."},
};

static const GmPairStep steps_keeloq[] = {
    {.title = "1. Pick the maker",
     "KeeLoq gates need the manufacturer's key. GarageMate lists the keys "
     "already on your SD card.\n\n"
     "If the maker is missing, the gate cannot be paired this way."},
    {.title = "2. Press LEARN",
     "Find the LEARN/PROG/SET button on the receiver board, usually inside the "
     "gate motor housing. Press it once."},
    {.title = "3. Transmit",
     "Press OK to send the new remote code.",
     true},
    {.title = "4. Confirm",
     "The receiver LED or beeper confirms. Test with the OPEN screen."},
};

static const GmPairStep steps_fixed_gate[] = {
    {.title = "1. Find LEARN",
     "Open the receiver housing on the gate motor. Look for a small button "
     "marked LEARN, PROG, SET or RADIO, next to an LED."},
    {.title = "2. Press LEARN",
     "Press it once. The LED lights or starts blinking, meaning the receiver "
     "is waiting for a code."},
    {.title = "3. Transmit",
     "Press OK to send a freshly generated random code.",
     true},
    {.title = "4. Confirm",
     "The LED turns off or flashes to confirm it stored the code. Test with "
     "the OPEN screen."},
};

/*
 * The brand table.
 *
 * To add a brand: append an entry here and, if it needs a new walkthrough, a
 * steps_* array above. Nothing else in the app needs to know about it.
 */
static const GmBrand brands[] = {
    {
        .id = "chamberlain_sp2",
        .display = "Chamberlain / LiftMaster",
        .hint = "Security+ 2.0, yellow LEARN",
        .kind = GmProtoSecPlusV2,
        .protocol = "Security+ 2.0",
        .keeloq_mfg = NULL,
        .bits = 0,
        .te = 0,
        // Both values mirror the stock firmware's own Security+ 2.0 generator,
        // where the mask is commented "850LM pairing".
        .serial_mask = 0x7FFFF3FC,
        .counter_start = 0xE500000,
        .freqs = {315000000, 310000000, 390000000},
        .freq_count = 3,
        .button = 0x68,
        .frame_repeat = 10,
        .rolling = true,
        .multiband = true,
        .steps = steps_chamberlain_sp2,
        .step_count = COUNT_OF(steps_chamberlain_sp2),
    },
    {
        .id = "chamberlain_sp1",
        .display = "Chamberlain (older)",
        .hint = "Security+ 1.0, coloured LEARN",
        .kind = GmProtoManual,
        .protocol = "Security+ 1.0",
        .keeloq_mfg = NULL,
        .bits = 0,
        .te = 0,
        .freqs = {390000000, 315000000},
        .freq_count = 2,
        .button = 0,
        .frame_repeat = 10,
        .rolling = true,
        .steps = steps_chamberlain_sp1,
        .step_count = COUNT_OF(steps_chamberlain_sp1),
    },
    {
        .id = "chamberlain_fixed",
        .display = "Chamberlain (vintage)",
        .hint = "DIP switches, no rolling code",
        .kind = GmProtoFixed,
        .protocol = "Cham_Code",
        .keeloq_mfg = NULL,
        .bits = 9,
        .te = 0,
        .freqs = {390000000, 315000000},
        .freq_count = 2,
        .button = 0,
        .frame_repeat = 12,
        .rolling = false,
        .steps = steps_chamberlain_fixed,
        .step_count = COUNT_OF(steps_chamberlain_fixed),
    },
    {
        .id = "genie",
        .display = "Genie / Overhead Door",
        .hint = "Intellicode - learn from remote",
        .kind = GmProtoGenie,
        .protocol = "Genie",
        .keeloq_mfg = NULL,
        .bits = GM_GENIE_BIT_COUNT,
        .te = 0,
        .freqs = {315000000, 390000000},
        .freq_count = 2,
        .button = 0,
        .frame_repeat = 0,
        .rolling = true,
        .steps = steps_genie,
        .step_count = COUNT_OF(steps_genie),
    },
    {
        .id = "keeloq",
        .display = "KeeLoq gate",
        .hint = "DoorHan, Beninca, AN-Motors...",
        .kind = GmProtoKeeLoq,
        .protocol = "KeeLoq",
        .keeloq_mfg = "DoorHan",
        .bits = 0,
        .te = 0,
        // KeeLoq serials are 28-bit.
        .serial_mask = 0x0FFFFFFF,
        .counter_start = 0,
        .freqs = {433920000, 315000000, 868350000},
        .freq_count = 3,
        .button = 0x2,
        .frame_repeat = 10,
        .rolling = true,
        .steps = steps_keeloq,
        .step_count = COUNT_OF(steps_keeloq),
    },
    {
        .id = "came",
        .display = "CAME gate",
        .hint = "Fixed code, 12 bit",
        .kind = GmProtoFixed,
        .protocol = "CAME",
        .keeloq_mfg = NULL,
        .bits = 12,
        .te = 0,
        .freqs = {433920000, 868350000, 315000000},
        .freq_count = 3,
        .button = 0,
        .frame_repeat = 12,
        .rolling = false,
        .steps = steps_fixed_gate,
        .step_count = COUNT_OF(steps_fixed_gate),
    },
    {
        .id = "nice_flo",
        .display = "Nice FLO gate",
        .hint = "Fixed code, 12 bit",
        .kind = GmProtoFixed,
        .protocol = "Nice FLO",
        .keeloq_mfg = NULL,
        .bits = 12,
        .te = 0,
        .freqs = {433920000, 868350000},
        .freq_count = 2,
        .button = 0,
        .frame_repeat = 12,
        .rolling = false,
        .steps = steps_fixed_gate,
        .step_count = COUNT_OF(steps_fixed_gate),
    },
    {
        .id = "princeton",
        .display = "Fixed-code gate",
        .hint = "Princeton / generic 24 bit",
        .kind = GmProtoFixed,
        .protocol = "Princeton",
        .keeloq_mfg = NULL,
        .bits = 24,
        .te = 400,
        .freqs = {433920000, 315000000, 390000000},
        .freq_count = 3,
        .button = 0,
        .frame_repeat = 12,
        .rolling = false,
        .steps = steps_fixed_gate,
        .step_count = COUNT_OF(steps_fixed_gate),
    },
    {
        .id = "linear",
        .display = "Linear / Multi-Code",
        .hint = "Fixed code, 10 bit",
        .kind = GmProtoFixed,
        .protocol = "Linear",
        .keeloq_mfg = NULL,
        .bits = 10,
        .te = 0,
        .freqs = {318000000, 315000000, 390000000},
        .freq_count = 3,
        .button = 0,
        .frame_repeat = 12,
        .rolling = false,
        .steps = steps_fixed_gate,
        .step_count = COUNT_OF(steps_fixed_gate),
    },
};

const GmBrand* gm_brands(void) {
    return brands;
}

size_t gm_brand_count(void) {
    return COUNT_OF(brands);
}

const GmBrand* gm_brand_at(size_t index) {
    if(index >= COUNT_OF(brands)) return NULL;
    return &brands[index];
}

const GmBrand* gm_brand_by_id(const char* id) {
    if(id == NULL) return NULL;
    for(size_t i = 0; i < COUNT_OF(brands); i++) {
        if(strcmp(brands[i].id, id) == 0) return &brands[i];
    }
    return NULL;
}

size_t gm_brand_index(const GmBrand* brand) {
    for(size_t i = 0; i < COUNT_OF(brands); i++) {
        if(&brands[i] == brand) return i;
    }
    return 0;
}

void gm_format_frequency(uint32_t frequency, char* out, size_t out_size) {
    furi_assert(out);
    // Frequencies are whole kHz in practice, so integer maths keeps this exact.
    uint32_t mhz = frequency / 1000000UL;
    uint32_t hundredths = (frequency % 1000000UL) / 10000UL;
    snprintf(out, out_size, "%lu.%02lu MHz", (unsigned long)mhz, (unsigned long)hundredths);
}
