/**
 * @file gm_brands.h
 * @brief Catalogue of supported opener brands and their pairing walkthroughs.
 *
 * Everything that differs between a Chamberlain opener and a CAME gate lives in
 * one table in gm_brands.c: which Sub-GHz protocol to speak, which frequencies
 * to offer, how many times to repeat a burst, and the human instructions shown
 * during pairing. Adding a brand means adding one entry there -- no scene or
 * radio code needs to change.
 */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Maximum frequencies offered for a single brand. */
#define GM_FREQ_MAX 3

/** Maximum walkthrough steps for a single brand. */
#define GM_STEPS_MAX 6

/** Length of a brand identifier as stored in a .door file. */
#define GM_BRAND_ID_MAX 24

/**
 * How GarageMate produces a transmittable payload for a brand.
 *
 * The first three kinds are generated by us; GmProtoManual covers brands the
 * stock firmware cannot synthesise, where we guide the user instead.
 */
typedef enum {
    /** Chamberlain/LiftMaster Security+ 2.0, via the firmware's generator. */
    GmProtoSecPlusV2,
    /** KeeLoq rolling code, keyed by a manufacturer name from the keystore. */
    GmProtoKeeLoq,
    /** Fixed-code protocols (Cham_Code, Princeton, CAME, Nice FLO, Linear). */
    GmProtoFixed,
    /** No generator available -- the walkthrough explains the alternative. */
    GmProtoManual,
} GmProtoKind;

/** One screen of the pairing walkthrough. */
typedef struct {
    const char* title;
    const char* body;
    /** True when this step offers a "Send" button instead of plain "Next". */
    bool transmit;
} GmPairStep;

/** A supported opener family. */
typedef struct {
    /** Stable identifier persisted in .door files. Never change these. */
    const char* id;
    /** Name shown in the brand picker. */
    const char* display;
    /** One-line disambiguator, e.g. "Yellow learn button, 2011+". */
    const char* hint;

    GmProtoKind kind;
    /** Sub-GHz protocol name as registered in the firmware, e.g. "Security+ 2.0". */
    const char* protocol;
    /** Manufacturer key name for GmProtoKeeLoq, otherwise NULL. */
    const char* keeloq_mfg;
    /** Payload width in bits for GmProtoFixed, otherwise 0. */
    uint16_t bits;
    /** Symbol period in microseconds for GmProtoFixed protocols that need it. */
    uint32_t te;

    /**
     * Bits a serial number is allowed to use.
     *
     * Not cosmetic: Security+ 2.0 openers only act on remotes whose serial
     * follows the pattern a factory remote would have, so a random serial can
     * be accepted during LEARN and then ignored afterwards.
     */
    uint32_t serial_mask;
    /**
     * First rolling counter value.
     *
     * Real remotes ship with a counter well away from zero, and the stock
     * firmware's own generator starts Security+ 2.0 at 0xE500000.
     */
    uint32_t counter_start;

    /** Frequencies offered during setup; freqs[0] is the default. */
    uint32_t freqs[GM_FREQ_MAX];
    uint8_t freq_count;

    /** Button/channel code baked into the generated remote. */
    uint8_t button;
    /** How many times a single press repeats the burst. */
    uint8_t repeats;
    /** True when the code changes on every press. */
    bool rolling;
    /**
     * True when receivers of this brand listen across every frequency in
     * @c freqs at once, so one press should go out on all of them.
     */
    bool multiband;

    const GmPairStep* steps;
    size_t step_count;
} GmBrand;

/** @return pointer to the brand table. */
const GmBrand* gm_brands(void);

/** @return number of entries in the brand table. */
size_t gm_brand_count(void);

/** @return brand at @p index, or NULL when out of range. */
const GmBrand* gm_brand_at(size_t index);

/** @return brand whose id matches @p id, or NULL when unknown. */
const GmBrand* gm_brand_by_id(const char* id);

/** @return index of @p brand in the table, or 0 when not found. */
size_t gm_brand_index(const GmBrand* brand);

/** Format @p frequency as "315.00 MHz" into @p out. */
void gm_format_frequency(uint32_t frequency, char* out, size_t out_size);

#ifdef __cplusplus
}
#endif
